---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  require_chef_omnibus: 13.5.3
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows10pro
    driver_config:
      box: hieunb/windows10pro
      customize:
        cpus: 2
        memory: 2560
      gui: true
      communicator: winrm
    transport:
      name: winrm
      username: vagrant
      password: vagrant

suites:
  - name: default
    run_list:
      - recipe[googlechrome::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
